# Generated by Django 3.2.9 on 2021-12-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_subcategory_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
