# Generated by Django 3.2.9 on 2021-12-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_variation'),
        ('cart', '0003_auto_20211209_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='home.Variation'),
        ),
    ]
