# Generated by Django 3.2.9 on 2021-12-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211215_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='taste',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='weight',
        ),
    ]
